# Generated by Django 3.2.7 on 2023-06-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='socio',
            name='ruc',
            field=models.IntegerField(),
        ),
    ]
