# Generated by Django 3.2.7 on 2023-06-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230607_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='ruc',
            field=models.IntegerField(null=True),
        ),
    ]
