# Generated by Django 3.2.7 on 2023-06-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_socio_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cedula',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='ruc',
            field=models.IntegerField(),
        ),
    ]
