# Generated by Django 3.2.7 on 2023-06-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230607_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socios',
            new_name='Socio',
        ),
    ]
