# Generated by Django 3.2.7 on 2023-06-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_socios_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='ruc',
            field=models.BigIntegerField(),
        ),
    ]
